- org-cyf-itd/content/steps/four/index.md
> Changed title in ITD step4 index.md

- org-cyf-itd/content/blocks/step-3/instructions/index.md
Changed step 3 instruction index.md description and links to Scrimba from khan , also deleted YT link
- [ y] Block 3, instructions
- [ y] I have read the [contributing guidelines](CONTRIBUTING.MD)
- [ y] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [ y] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [y ] I have run my code to check it works
- [y ] My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)
> Changed step 3 instruction index.md description and links to Scrimba from khan 

- org-cyf-itd/content/blocks/how-itd-works/what-is-itd/index.md
Added content to Manual section in the itd how it works
> content changes to manual

- org-cyf-itd/content/blocks/common-issues/index.md
- org-cyf-itd/content/blocks/step-3/acceptance/index.md
- org-cyf-itd/content/blocks/step-3/submission/index.md
Changed CYF to MC content (Slack and laptops)
yes, how to get help
- [y ] I have read the [contributing guidelines](CONTRIBUTING.MD)
- [ y] I have checked my spelling and grammar with an [automated tool](https://www.grammarly.com/grammar-check)
- [ y] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
- [y ] I have run my code to check it works
- [y ] My changes follow our [Style Guide](https://curriculum.codeyourfuture.io/guides/code-style-guide)
> Changed common module "how to get help"

- org-cyf-itd/content/blocks/common-issues/index.md
> specify about laptops

- org-cyf-itd/content/blocks/step-3/acceptance/index.md
> changed 5 , aka step 4

- org-cyf-itd/content/blocks/step-4/extend/index.md
- org-cyf-itd/content/blocks/step-4/instructions/index.md
- org-cyf-itd/content/blocks/step-4/submission/index.md
commits for step 5 (CodePen)
NO
- [x ] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
> commits for step 5 (CodePen)

- org-cyf-itd/content/blocks/help/index.md
updated the help section of itd
- [ x] Block/s - help
> updated the help section of itd

- org-cyf-itd/content/blocks/help/index.md
- org-cyf-itd/content/blocks/step-0/instructions/index.md
- org-cyf-itd/content/blocks/step-0/submission/index.md
Changed CYF specific content to MC content in step 0
NO
##
> Updated Zero (what I thought was prep until I noticed it isn`t, sorry!)

- org-cyf-itd/content/steps/zero/index.md
changed the title "Join the MigraoCode ITD"
> changed the title "Join the MigraoCode ITD" in "steps; zero"

- org-cyf-itd/content/blocks/how-itd-works/what-is-itd/index.md
> finish What is ITD

- org-cyf-itd/content/steps/five/index.md
- org-cyf-itd/content/steps/two/index.md
"commenting out some blocks in step 5 for the CodePen website
> "commenting out some blocks"

- org-cyf-itd/content/_index.md
- org-cyf-itd/content/steps/five/index.md
- org-cyf-itd/content/steps/four/index.md
- org-cyf-itd/content/steps/three/index.md
- org-cyf-itd/content/steps/two/index.md
Renamed and renumbered some so they are orderly on the website.
Also took out workshops and one of the extensions in step 5 (codepen website, took out "extend")
> changed the "menu"

- common-theme/assets/styles/02-variables/colors.scss
- org-cyf-itd/content/_index.md
- org-cyf-itd/content/steps/five/index.md
- org-cyf-itd/content/steps/four/index.md
- org-cyf-itd/content/steps/one/index.md
- org-cyf-itd/content/steps/six/index.md
- org-cyf-itd/content/steps/three/index.md
- org-cyf-itd/content/steps/zero/index.md
I changed the structure and a few styling details
We now have 3 columns and the blocks show accordingly
> changed the structure and a few styling details

- org-cyf-itd/content/blocks/step-0/instructions/index.md
> fixed spelling

- org-cyf-itd/content/steps/two/index.md
> taking out the AI cover letter part

- org-cyf-itd/content/blocks/how-itd-works/submission/index.md
just a small change
- [x ] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
> small change to title of submission

- common-docs/hugo.toml
- org-cyf-theme/hugo.toml
changed links from CYF to OCC and MC
NO
NO
- [x ] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
> changed links to OCC and MC

- org-cyf-itd/content/blocks/step-1-using-slack/acceptance/index.md
- org-cyf-itd/content/blocks/step-1-using-slack/instructions/index.md
- org-cyf-itd/content/blocks/step-1-using-slack/submission/index.md
Updated step 1 (using Slack and Search engines)
NO
> Updated step 1 (using Slack and Search engines)

- org-cyf-itd/content/blocks/step-0/instructions/index.md
> added link to itd slack channel

- common-content/en/blocks/morning-orientation/index.md
- org-cyf-how-this-works/content/prep/index.md
- org-cyf-itd/content/blocks/groups/newcomers/index.md
- org-cyf-itp/content/welcome/_index.md
- org-cyf-itp/content/welcome/day-plan/index.md
Changing mainly block names
no
no
- [x ] I have previewed my changes to check the [markdown renders](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) as I intend
> Changing mainly block names

- common-content/en/blocks/workshop/index.md
- org-cyf-itp/content/data-flows/sprints/1/day-plan/index.md
- org-cyf-itp/content/data-flows/sprints/2/day-plan/index.md
- org-cyf-itp/content/data-groups/sprints/1/day-plan/index.md
- org-cyf-itp/content/data-groups/sprints/3/day-plan/index.md
1. This Pull request changes the names on the CYF Workshop links to Migracode but does not change the links
2. It hides the second study blocks and the Code review blocks in each day plan.
Issue : Data Groups and Data flows
> Update Migracode Curriculum– Edits from Phyllis Branch

- common-content/en/blocks/lunch/index.md
- common-docs/content/common-theme/pages/day-plan.md
- org-cyf-itp/content/data-flows/sprints/2/day-plan/index.md
- org-cyf-itp/content/onboarding/sprints/1/day-plan/index.md
- org-cyf-itp/content/welcome/day-plan/index.md
changed community lunch description to reflect what we will do
no
> changed community lunch

- common-content/en/blocks/lunch/index.md
> Update lunch title

- org-cyf-itp/content/onboarding/sprints/1/day-plan/index.md
> changed file path Bikes for refugees

- org-cyf-itd/content/blocks/how-itd-works/email/index.md
- org-cyf-itd/content/blocks/step-3/instructions/index.md
- org-cyf-itd/content/steps/three/index.md
> changed ITD criteria to take out step2

- common-content/en/blocks/disclaimer-mc/index.md
- org-cyf-itp/content/onboarding/sprints/1/day-plan/index.md
> added disclaimer for exercise

- common-content/en/blocks/lunch/index.md
- common-content/en/module/onboarding/application/index.md
- common-content/en/module/onboarding/goals/index.md
edited lunch description to include what we agreed on (scheduled community lunches)
- [
NO
LUNCH
> edited lunch description

- common-content/en/blocks/lunch/index.md
- org-cyf-itp/content/data-flows/project/prep/index.md
- org-cyf-itp/content/data-flows/sprints/2/day-plan/index.md
- org-cyf-itp/content/data-flows/sprints/3/day-plan/index.md
- org-cyf-itp/content/data-flows/success/index.md
- org-cyf-itp/content/data-groups/sprints/1/day-plan/index.md
- org-cyf-itp/content/data-groups/success/index.md
This has updated the content on the prep pages of the Product page
> Product page updates

- org-cyf-itp/content/data-flows/success/index.md
> reworded succes intstructions

- org-cyf-itd/content/blocks/how-itd-works/duration/index.md
- org-cyf-itp/content/data-flows/project/prep/index.md
> changed date of start of course

- common-content/en/blocks/disclaimer-mc/index.md
- org-cyf-itp/content/structuring-data/sprints/1/day-plan/index.md
> changed the disclaimer

- common-content/en/module/induction/learning-as-community/index.md
- org-cyf-itp/content/safe-guarding/index.md
> changes to "welcome to MigraCode"

- common-content/en/blocks/afternoon-break/index.md
- org-cyf-itp/content/data-flows/prep/index.md
- org-cyf-itp/content/data-flows/project/prep/index.md
- org-cyf-itp/content/data-groups/sprints/1/day-plan/index.md
- org-cyf-itp/content/data-groups/sprints/3/day-plan/index.md
This PR resolves merge conflicts from the latest changes in main and finalizes updates to multiple files across modules.
Specifically:
- Resolved merge conflicts in index.md files across the ITP curriculum
Made content updates to:
- afternoon-break/index.md
- sprints/3/day-plan/index.md
Ensured all changes from both branches are properly merged for deployment
Includes updates to common-content/en/blocks/afternoon-break/index.md
> Phyllis branch

- org-cyf-itp/content/data-groups/sprints/1/day-plan/index.md
Changes the time structure on the day plan for sprint 1  in Data groups.
> Updates to time:DG/Sprint 1 day-plan

- org-cyf-itp/content/data-flows/sprints/1/day-plan/index.md
- org-cyf-itp/content/data-flows/sprints/2/day-plan/index.md
- org-cyf-itp/content/data-flows/sprints/3/day-plan/index.md
> Updates to time:data flows day-plan

- org-cyf-itp/content/data-flows/success/index.md
- org-cyf-itp/content/data-groups/success/index.md
> Disclaimer for success page

- common-content/en/blocks/disclaimer-mc/index.md
- org-cyf-itp/content/data-flows/project/prep/index.md
- org-cyf-itp/content/data-flows/success/index.md
- org-cyf-itp/content/data-groups/success/index.md
> Updates to the product page

- common-content/en/blocks/disclaimer-mc/index.md
> New changes to disclaimer block

- common-content/en/blocks/disclaimer-mc/index.md
- org-cyf-itp/content/data-flows/success/index.md
- org-cyf-itp/content/data-groups/success/index.md
> Disclaimer Info added to success

- org-cyf-itp/content/safe-guarding/index.md
Changed the wording in "Safeguarding Module" to make if more clear and prevent misunderstandings.
NO
> Changed the wording in "Safeguarding Module"

- org-cyf-itp/content/onboarding/sprints/3/prep/index.md
> added disclaimer to exercise

- org-cyf-itp/content/data-groups/sprints/2/day-plan/index.md
- org-cyf-itp/content/data-groups/sprints/3/day-plan/index.md
> Changed disclaimer block to a nested one
